name: nearby_connections_example
description: "Demonstrates how to use the nearby_connections plugin."
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  nearby_connections:
    # When depending on this package from a real application you should use:
    #   nearby_connections: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  location: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
